apiVersion: v1
entries:
  ravendb-cluster:
  - apiVersion: v1
    appVersion: "7.2"
    created: "2026-02-02T14:24:40.4331805+01:00"
    description: Chart for RavenDB Cluster
    digest: b903a4e06e2974e9acd123c186e871fe30f6f2fa57319a6b5c9f851a66798481
    icon: https://ravendb.net/img/repository-icon.svg
    name: ravendb-cluster
    urls:
    - ravendb-cluster/package/ravendb-cluster-2.0.4.tgz
    version: 2.0.3
generated: "2026-02-02T14:25:41.296403+01:00"
