apiVersion: v1
entries:
  ravendb-cluster:
  - apiVersion: v1
    appVersion: "7.2"
    created: "2026-02-17T14:18:36.3259614+01:00"
    description: Chart for RavenDB Cluster
    digest: b903a4e06e2974e9acd123c186e871fe30f6f2fa57319a6b5c9f851a66798481
    icon: https://ravendb.net/img/repository-icon.svg
    name: ravendb-cluster
    urls:
    - ravendb-cluster/package/ravendb-cluster-2.1.0.tgz
    version: 2.1.0
generated: "2026-02-17T14:18:36.3238534+01:00"
